const fs = require('fs');

console.log('----------------------------------------');
console.log('🔍 Checking Environment Variables...');

const openAqParams = process.env.OPENAQ_API_KEY ? `FOUND (Length: ${process.env.OPENAQ_API_KEY.length})` : 'MISSING ❌';
const waqiParams = process.env.WAQI_API_TOKEN ? `FOUND (Length: ${process.env.WAQI_API_TOKEN.length})` : 'MISSING ❌';

console.log(`OPENAQ_API_KEY: ${openAqParams}`);
console.log(`WAQI_API_TOKEN: ${waqiParams}`);

const configContent = `// Generated by Netlify Build
const config = {
    OPENAQ_API_KEY: '${process.env.OPENAQ_API_KEY || ""}',
    WAQI_API_TOKEN: '${process.env.WAQI_API_TOKEN || ""}'
};

if (typeof window !== 'undefined') {
    window.APP_CONFIG = config;
}
`;

fs.writeFileSync('config.js', configContent);
console.log('----------------------------------------');
console.log('✅ config.js generated');
console.log('----------------------------------------');
