const fs = require('fs');

const configContent = `// Generated by Netlify Build
const config = {
    OPENAQ_API_KEY: '${process.env.OPENAQ_API_KEY || ""}',
    WAQI_API_TOKEN: '${process.env.WAQI_API_TOKEN || ""}'
};

if (typeof window !== 'undefined') {
    window.APP_CONFIG = config;
}
`;

fs.writeFileSync('config.js', configContent);
console.log('✅ config.js generated successfully with env vars');
